### ISSUE TITLE
How is this supposed to work exactly?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/kitty-themes-feedstock#1]
Is this just providing the files so we can copy them, or are they on the kitty path such that `include ...` will work properly?

**Comment by scopatz** [comment]
My kitty.conf contains a line like:

```
include /home/scopatz/miniconda/share/kitty-themes/SeaShells.conf
```

**Comment by CJ-Wright** [comment]
Ah ok awesome!
